### ISSUE TITLE
Warning or Error on projection mismatch

### ISSUE THREAD

**Issue by Lvulis** [jonschwenk/RivGraph#18]
Jon, a nice (and easy) feature would be if a non-critical warning should pop if the CRS of the channel mask & the inletnodes and/or shoreline don't match. Now it is a simple reprojection without warning that it happened. Accidentally trimmed a Siberian delta with the Mackenzie and was befuddled why it was so bad.

Example in delta_utils.py:
```
 inlets_gpd = gpd.read_file(inlets_shp)
    # inlets_epsg = int(inlets_gpd.crs['init'].split(':')[1])
    inlets_epsg = inlets_gpd.crs.to_epsg()
    mask_epsg = gu.get_EPSG(gdobj)
    if inlets_epsg - mask_epsg != 0:
        inlets_gpd = inlets_gpd.to_crs(epsg=mask_epsg)
```

I see this in find_inlet_nodes and clip_by_shoreline, don't see anywhere else.

**Comment by jonschwenk** [comment]
The reason that I didn't include a warning here is that there is no stored modification to the user's input data; i.e. the reprojected inlets_gpd never gets re-written or re-used, it's just a one-off. However, you raise a good point that it could be helpful to issue a warning when the CRSs don't match. Will add this to for both inlet nodes and shoreline.

**Comment by jonschwenk** [comment]
Added print statements to inform user that CRSs are mismatched and will be reprojected.
