### ISSUE TITLE
bug: remove_two_link_nodes connectivity update

### ISSUE THREAD

**Issue by elbeejay** [jonschwenk/RivGraph#32]
Seems like there can be instances when `remove_two_link_nodes()` is called (during network pruning), and during the node connectivity updating sometimes the function tries to "pop" an empty set ([Line 932](https://github.com/jonschwenk/RivGraph/blob/7a5d2e67b0bd3335a4f20d8bd6f70c8660e30065/rivgraph/ln_utils.py#L932)) which throws an error.

I think a quick fix could be sticking those few lines of code in a `try-except` statement, although I will look into the root cause of the bug to properly resolve it.

**Comment by jonschwenk** [comment]
Were you using the latest version, and can you provide a repeatable example dataset?

I remember having this issue after I removed the automatic "add_aritificial_nodes" functionality, but I resolved it for the test cases I had at hand. I've avoided the try/except fixes so far because they mask the source issue.

**Comment by elbeejay** [comment]
> Were you using the latest version, and can you provide a repeatable example dataset?

Yes and yes I believe. Just double checked my dependencies to make sure they matched what RivGraph requires, and reinstalled the package based on the current code in the repository to make sure things were current.

Files (even compressed) are too big for GitHub but I'll share them with you directly.

**Comment by jonschwenk** [comment]
Ok, here is what was happening. When you create your mask, you are not filtering out all the smaller objects that are not connected to the channel network. RivGraph was designed to handle this, but you found a case that I hadn't yet encountered.

Here is the problem:
![image](https://user-images.githubusercontent.com/14874485/103046951-39d22500-4547-11eb-8673-0fba31bf109e.png)
After pruning the "dangling links" (i.e. those connected to the network at only one end), this subnetwork looks like this:

![image](https://user-images.githubusercontent.com/14874485/103047012-64bc7900-4547-11eb-8e75-c13d9e84b43f.png)

The function `remove_two_link_nodes` is then run iteratively. This function looks for nodes of degree two (have only two links connected) and deletes the node then "fuses" the links. You can see that all the nodes in this subnetwork are "two link nodes", and so the entire subnetwork will eventually reduce to a single node with a link that starts and ends at the node. The implementation did not account for this case (where the connectivity has two link ids, but they are the same). I have added a few lines to catch and handle these cases by deleting the subnetwork entirely.

The updated code now runs your example without errors.
