### ISSUE TITLE
bug: CRS not always compliant with geopandas

### ISSUE THREAD

**Issue by elbeejay** [jonschwenk/RivGraph#33]
There seems to be a gap between what the various geospatial packages accept as valid CRS information.

For example, the below CRS information is read by RivGraph using `GDAL`, and can works with the `GDAL`-based functions like `to_geotiff()`, but does not work with the `geopandas` based functions like `to_geovectors()`. 

```
<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- undefined
Datum: World Geodetic System 1984
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich
```

A suitable fix for this specific case was to manually set the crs information stored in the `delta` class to `delta.crs = "EPSG:4326"` as that is recognized and accepted by `geopandas`. 

Need to do some poking around to figure this out as I doubt it is an uncommon problem... other geospatial projects that depend on `GDAL` and `geopandas` must have some sort of solution to handle this mismatch. 

EDIT: This bug might just be a weird line in RivGraph somewhere, seems like `geopandas` is designed to work with `pyproj` CRS information...

**Comment by elbeejay** [comment]
Well this was an "issue" on my end. Checked my local packages and found I was using `geopandas` v0.6.1. Upgrading to v0.7.0 which is what RivGraph expects solved this!

**Comment by jonschwenk** [comment]
Glad you figured it out--the pin to geopandas 0.7 was in order to use the latest version of pyproj which handles the CRS management. As you discovered, the code won't play nicely with older versions.
