### ISSUE TITLE
Link in the README leads to 404

### ISSUE THREAD

**Issue by leotrs** [jonschwenk/RivGraph#40]
At the end of the About section in the README, there is link to a "delta channel network" that links to https://github.com/jonschwenk/RivGraph/blob/master/examples/delta_example.py.ipynb. This leads to a 404 on my end.

**Comment by leotrs** [comment]
I just realized that the extension in the link is wrong (.py.ipynb instead of just .ipynb)

**Comment by jonschwenk** [comment]
Good eye, [fixed](https://github.com/jonschwenk/RivGraph/commit/10d44220690db51f67c18dd20db88c9f3b5c50e9).

**Comment by kbarnhart** [comment]
openjournals/joss-reviews/issues/2952
