### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by leotrs** [jonschwenk/RivGraph#41]
On the first page of the documentation, there is a broken link to the FAQ:

![2021-01-28-093631_793x55_scrot](https://user-images.githubusercontent.com/1096704/106153234-523bed80-614c-11eb-8aeb-51778853173c.png)

**Comment by jonschwenk** [comment]
We have not yet created those pages. [Removed the link](https://github.com/jonschwenk/RivGraph/commit/cad342a96cbc65bb7dcbf02bcca474c73f4a9a23) for now.

**Comment by kbarnhart** [comment]
openjournals/joss-reviews/issues/2952
