### ISSUE TITLE
Failure on a tidal inlet

### ISSUE THREAD

**Issue by Lvulis** [jonschwenk/RivGraph#47]
Had an issue with the following tidal inlet where remove_all_spurs in prune_network removes the entire network on the first run. Relevant data attached [here](https://drive.google.com/file/d/11vN036VzYSxdEb6ktzyzOJa9I1l8rgEv/view?usp=sharing).
Note that I have a slightly modified version of remove_all_spurs, which will keep a single link channel network (used for some boring river mouths). Only relevant because it ensures the entire network isn't pruned, but keeps the link attached to the inlet. See the modification below

```
        # Remove all the nodes with only two links attached
        links, nodes = remove_two_link_nodes(links, nodes, dontremove)
 
        # For single channel (no loops & single outlet) networks,
        # prevent overpruning beyond a single network with 2 nodes.
        if (links['n_networks'] == 1) & (len(nodes['conn']) == 2):
            ct = 0
            
        if ct == 0:
            stopflag = 1

    return links, nodes
```

**Comment by Lvulis** [comment]
Should comment that this wasn't the best fix, and in fact use a slightly modified version of this. Instead of ct == 0, I use ct <= ctmax, and also add an option to use a negative ctmax. ctmax is passed as an argument to remove_all_spurs. This has worked in other cases and prevented overpruning, especially in relatively 'simple' networks. 
```
# Remove all the nodes with only two links attached
        links, nodes = remove_two_link_nodes(links, nodes, dontremove)
        
         # For single channel (no loops & single outlet) networks,
        # prevent overpruning beyond a single network with 2 nodes.
        if (links['n_networks'] == 1) & (len(nodes['conn']) == 2):
            ct = 0
        
        if (ctmax == -1) or (ct <= ctmax):
            stopflag = 1
```

**Comment by Lvulis** [comment]
Leaving some notes here if you guys have any ideas. Overpruning of the network continues to be an issue especially removal of the outlet nodes after identification using `clip_by_shoreline` and destroying the network. I tried using `ctmax = -1` (i.e. run `remove_all_spurs` for only one iteration), and then identifying outlets. The resulting outlets have connections through the ocean (looking like a circular graph basically). Then `remove_disconnected_bridge_links` kills the network and there's basically a couple loops out of the inlet and that's all. Data is attached [here](https://drive.google.com/open?id=1S6CuaNGRV33E4kTBm95X6LvpwhTOWUs0&authuser=lvulis%40uci.edu&usp=drive_fs):

**Comment by elbeejay** [comment]
Threw the network image, inlet, and shoreline into QGIS and got the following picture:

![image](https://user-images.githubusercontent.com/1770513/117213377-27071100-adc1-11eb-8a60-b34e19448540.png)

Not sure if I've done something wrong with this data, but if this picture is right, then I guess I wouldn't expect RivGraph to extract the network successfully.

**Comment by Lvulis** [comment]
Can I delete this out of embarrassment? Need another coffee, didn't check if the shoreline was good this whole time.

**Comment by jonschwenk** [comment]
Haha, @Lvulis we're gonna leave it up because someone else may one day forget to check their shoreline. No need to be embarrassed, just laugh and learn.
