### ISSUE TITLE
OSError: exception: access violation writing 0x0000000300000003, while running to_geovectors() function

### ISSUE THREAD

**Issue by fluvialgeomorf** [jonschwenk/RivGraph#67]
Hi! Any ideas why I am getting this error? Also getting a similar error when running the compute.mesh() function. 
Seems to be related to the shapely package (I have the 1.7.1 version). 

Here is a screenshot of the full sequence of errors.
![OSError](https://user-images.githubusercontent.com/94083514/148468594-064139ad-d093-4a12-ac9a-3f2906fe9653.png)

Thanks! 
Tanya

**Comment by jonschwenk** [comment]
Hi Tanya, I can't tell from this traceback what the issue is. You could be right that it's related to how newer versions of shapely access geometries. The first thing I'd suggest is that you check the geometries to ensure they're normal shapely types.

Are you running the example or your own mask? If you can provide your mask, I can take a more detailed look.

**Comment by fluvialgeomorf** [comment]
Hi Jon -- for some reason, this is happening to me even with the older version of shapely.  
Also, I am using my own mask --  here it is. 
[YukonFlats.zip](https://github.com/jonschwenk/RivGraph/files/7825394/YukonFlats.zip)

**Comment by jonschwenk** [comment]
I cannot reproduce the issue. You might need to share your script. I am using rivgraph 0.4 and shapely 1.7.1. Here's what I get:

```
from rivgraph.classes import river

name = 'issue67'
path_to_mask = r"X:\Research\RivGraph\Bugs\Issue 67\YukonFlats\YukonBinary.tif"
results_folder = r"X:\Research\RivGraph\Bugs\Issue 67\Results"
es = 'EW'

br = river(name, path_to_mask, results_folder=results_folder, exit_sides=es, verbose=True)

br.skeletonize()
br.compute_network()
br.prune_network()
br.assign_flow_directions()
br.to_geovectors('all')
```

And in Q:

![image](https://user-images.githubusercontent.com/14874485/148473755-8a474175-51a5-407b-b0ee-3b12faff6b92.png)

Both the network and mesh export without error for me.

**Comment by jonschwenk** [comment]
A little bit of googling suggests that it [might be related to fiona/OSGeo dependencies](https://gis.stackexchange.com/a/306597/78446). For further clarification on my example above, I created a new environment from scratch using the [yml file in this repo](https://github.com/jonschwenk/RivGraph/blob/master/environment.yml). I'm on a Windows machine. Python 3.8 was installed. Hope that helps!

**Comment by fluvialgeomorf** [comment]
This is beautiful! 
I have a script similar to what you have but still giving the OSError -- installed rivgraph exactly as you did. But it sounds like the packages installed with RivGraph are interfering with the packages I already had on my computer being different versions. 
This is good -- I can take it from here. Will update when I solve the problem. 
Thanks for all the help, Jon.
