### ISSUE TITLE
Broken building/testing

### ISSUE THREAD

**Issue by jsta** [jonschwenk/RivGraph#74]
It seems like one (but not the only) issue causing the broken build is changes to networkx. Might try adding a requirement that it be < v2.7.

**Comment by jsta** [comment]
Another thing causing the brokenness is the use pytest.approx(a == b) instead of a == pytest.approx(b) in the tests.

**Comment by elbeejay** [comment]
Good idea, testing this [here](https://github.com/elbeejay/RivGraph/runs/5605445431?check_suite_focus=true).

**Comment by jsta** [comment]
All the remaining errors other than the approx and networkx errors are beyond my familiarity with the codebase.

**Comment by jonschwenk** [comment]
It also looks like it's trying to install rivgraph 0.2 instead of 0.4. Must be dependency issues.

**Comment by jsta** [comment]
That's because 0.2 is the version on https://anaconda.org/jschwenk/rabpro

**Comment by elbeejay** [comment]
[This environment](https://github.com/elbeejay/RivGraph/blob/fix-ci/environment.yml) resolves itself locally for me and I can run `from osgeo import gdal` but this is still breaking on the CI workflow. Will keep digging!

**Comment by jonschwenk** [comment]
> That's because 0.2 is the version on https://anaconda.org/jschwenk/rabpro

? RivGraph 0.4 is the latest conda version of RivGraph https://anaconda.org/jschwenk/rivgraph. Am I missing how rabpro plays into this at all?

**Comment by jsta** [comment]
Whoops my mistake

**Comment by jonschwenk** [comment]
@elbeejay Do you remember why we have the hard pin to shapely? I imagine that really hinders the enviornment solve...

**Comment by elbeejay** [comment]
> @elbeejay Do you remember why we have the hard pin to shapely? I imagine that really hinders the enviornment solve...

I do not recall the specific reason, but that is a good point

**Comment by jsta** [comment]
We're not technically testing the "build" since we're using a pinned dependency list in the CI rather than the conda solver. Should probably make a new issue if/when we want to test forward compatibility (e.g. with more recent versions of networkx and shapely).
