### ISSUE TITLE
Shoreline left_id error

### ISSUE THREAD

**Issue by Lvulis** [jonschwenk/RivGraph#8]
Jon you had this fixed previously, not sure exactly why my shoreline has a column named LEFT_FID and RG is only checking for 'id_left'. This fix you sent to me works (for delta_utils.py, clip_by_shoreline).

```python
    # Remove the links beyond the shoreline
    shore_int = gpd.sjoin(links_gdf, shore_gdf, op='intersects')
    # Find the proper column ID (left)
    leftid = [lid for lid in shore_int.columns if 'id' in lid.lower() and 'left' in lid.lower()][0]
    # Get ids of intersecting links
    cut_link_ids = shore_int[leftid].values
```

**Comment by jonschwenk** [comment]
Ok, will integrate this. The problem arises from how different versions of geopandas name the joined GeoDataFrame attributes.

**Comment by Lvulis** [comment]
Thanks good to know

**Comment by jonschwenk** [comment]
Updated the code for this. Documentation should specify that 'id' must be within a column name in the attribute table for the created shoreline.
