### ISSUE TITLE
Shoreline error bugout?

### ISSUE THREAD

**Issue by Lvulis** [jonschwenk/RivGraph#9]
I encounter the following error from pruning the network with the shoreline & inlet nodes I have. I am documenting this now in case you may know, but will look at it more further (bad shoreline, bad inlet nodes, etc.). If one of those, maybe this error type can give rise to good documentation. Apologies for all the late night notifications.

```python
...: ### Pruning the network

yukon.prune_network(path_shoreline='C:/Users/Lawrence Vulis/Documents/deltas/r_work/utm/yukon/outlines/Yukon_shoreline_v1.shp', path_inletnodes='C:/Users/Lawrence Vulis/Documents/deltas/r_work/utm/yukon/outlines/Yukon_inlet_nodes.shp')
Geotiff written to C:\Users\Lawrence Vulis\Documents\deltas\RG_experiments\LV_extraction\Results\Yukon\Yukon_skel.tif.
Resolving links and nodes...done.
links: dict_keys(['idx', 'conn', 'id', 'n_networks'])
nodes: dict_keys(['idx', 'conn', 'id'])
C:\Anaconda3\envs\geo_py37\lib\site-packages\pyproj\crs\crs.py:53: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  return _prepare_from_string(" ".join(pjargs))
C:\Users\Lawrence Vulis\Documents\deltas\RG_experiments\LV_extraction\Results\Yukon\Yukon_links.json
C:\Users\Lawrence Vulis\Documents\deltas\RG_experiments\LV_extraction\Results\Yukon\Yukon_nodes.json
Traceback (most recent call last):

  File "<ipython-input-356-11a37adc6754>", line 59, in <module>
    yukon.prune_network(path_shoreline='C:/Users/Lawrence Vulis/Documents/deltas/r_work/utm/yukon/outlines/Yukon_shoreline_v1.shp', path_inletnodes='C:/Users/Lawrence Vulis/Documents/deltas/r_work/utm/yukon/outlines/Yukon_inlet_nodes.shp')

  File "C:\Anaconda3\envs\geo_py37\lib\site-packages\rivgraph-0.2-py3.7.egg\rivgraph\rivgraph.py", line 513, in prune_network
    self.links, self.nodes = du.prune_delta(self.links, self.nodes, path_shoreline, path_inletnodes, self.gdobj)

  File "C:\Anaconda3\envs\geo_py37\lib\site-packages\rivgraph-0.2-py3.7.egg\rivgraph\deltas\delta_utils.py", line 56, in prune_delta
    links, nodes = clip_by_shoreline(links, nodes, shoreline_shp, gdobj)

  File "C:\Anaconda3\envs\geo_py37\lib\site-packages\rivgraph-0.2-py3.7.egg\rivgraph\deltas\delta_utils.py", line 174, in clip_by_shoreline
    lidx = links['id'].index(clid)

  File "C:\Anaconda3\envs\geo_py37\lib\site-packages\rivgraph-0.2-py3.7.egg\rivgraph\ordered_set.py", line 194, in index
    return self.map[key]

KeyError: -1

```

**Comment by jonschwenk** [comment]
Did you look at the shoreline I made for your mask? I linked to it in another issue, but here it is again: https://drive.google.com/open?id=1mYE-PkJ5lB5S2OkZ8jkmEbgIDyJtJtsS

**Comment by Lvulis** [comment]
Yep and it worked perfectly! Should have noted last night I also got my installation to get up to assigning directionality but can't resolve a cycle. So here the issue is something with the shoreline I used. I will look at it more in a bit. was hoping this may be useful for you - is the error informative at all? If I get the same on error on another delta does that mean I need to adjust my shoreline by x or y?

**Comment by jonschwenk** [comment]
Not sure. The shoreline should only intersect links at outlets, or links that will be removed during spur pruning. It should effectively delineate two separate subnetworks--the one you want to keep, and the one "in the ocean."  So your initial shoreline that surrounded the entire delta would likely throw some weird errors.

**Comment by Lvulis** [comment]
Ok that makes sense, i was mostly concerned with the tidal/ice zone on the northern edge. On my phone but noting your comment in the doc would be extremely helpful (although this may just be because I'm using masks I defined for the shrinkage analysis)

**Comment by Lvulis** [comment]
OK issue resolved:

The shoreline I used had these two fields, LEFT_FID and RIGHT_FID. This was causing the cut_link_ids to all be -1. I changed the fields to match that of your shoreline and it worked. So solution is to have id as a field with NA as the entry. I also fixed my shoreline to be the actual shoreline.

**Comment by jonschwenk** [comment]
I should make these header names explicit instead of relying on the default (seemingly changing) geopandas labels.

**Comment by Lvulis** [comment]
It seems that the "LEFT_FID" is not geopandas fault by the way but some issue with how it was generated originally (in Arc). If by header names being explicit you mean stating what fields the shoreline file should have, agreed!

**Comment by jonschwenk** [comment]
This has been addressed in the docs now: https://jonschwenk.github.io/RivGraph/issues/index.html
